#if !canImport(ObjectiveC)
import XCTest

extension SheetControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SheetControllerTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SheetControllerTests.__allTests__SheetControllerTests),
    ]
}
#endif
